service: covid-19-data-updater

provider:
  name: aws
  runtime: python3.6

functions:
  update_covid_data:
    handler: handler.update_data

  get_maximum_values:
    handler: maximumEncodedDayHandler.get_maximum_values
    events:
      - http:
          path: get_maximum_values
          method: get
          cors: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

package:
  exclude:
    - node_modules/**
    - venv/**
