service: covid-19-data-updater

provider:
  name: aws
  runtime: python3.6

functions:
  update_covid_data:
    handler: handler.update_data
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:PutObject
        Resource: "arn:aws:s3:::covid-visualization-data/*"

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

package:
  exclude:
    - node_modules/**
    - venv/**
